[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "indentation-converter"
version = "0.2.0"
description = "Convert indentation between spaces and tabs in text files and directories, ignoring hidden files, binary files, and files in .gitiginore."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
keywords = ["indentation", "tabs", "spaces", "converter"]

authors = [
    {name = "HenestrosaDev", email = "henestrosadev@gmail.com"}
]

classifiers = [
    "Intended Audience :: Developers",
    "Environment :: Console",
    "Topic :: Text Processing :: General",
    "Topic :: Utilities",
    "Operating System :: OS Independent",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Other OS",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]

dependencies = [
    "binaryornot==0.4.4",
    "pathspec==0.12.1"
]

[project.urls]
Homepage = "https://github.com/HenestrosaDev/indentation-converter"

[project.scripts]
# Corregido: Ahora apunta a la función 'main' dentro de '__main__.py'
indentation_converter = "indentation_converter.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]